### ISSUE TITLE
process.env.HOME is invalid for windows

### ISSUE THREAD

**Issue by si458** [nmarus/nexe-natives#5]
```
PS C:\Users\Simon\Documents\testapp> node .\index.js
internal/validators.js:124
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:424:7)
    at Object.<anonymous> (C:\Users\Simon\Documents\testapp\node_modules\nexe-natives\index.js:6:31)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Users\Simon\Documents\testapp\index.js:4:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
it is erroring out on the line 
`const defaultLocalPath = path.join(process.env.HOME, '.nexe_natives');`
however `process.env.HOME` is not set on Windows
line should be 
`const defaultLocalPath = path.join((process.platform == 'win32' ? process.env.USERPROFILE : process.env.HOME), '.nexe_natives');`

**Comment by Udxr** [comment]
I am having the same issue. Have you found a fix?

**Comment by si458** [comment]
> I am having the same issue. Have you found a fix?

Using my PR #7 fixes this issue
