### ISSUE TITLE
doesnt work with platform-folders

### ISSUE THREAD

**Issue by si458** [nmarus/nexe-natives#6]
i cant get this to work with the npm module 'platform-folders' ?
```
const platformfolders = require('nexe-natives')(require.resolve('platform-folders'));
console.log(platformfolders);
```
```
PS C:\Users\Simon\Documents\testapp> node .\index.js
internal/modules/cjs/loader.js:892
  throw err;
  ^
Error: Cannot find module 'bindings'
Require stack:
- C:\Users\Simon\.nexe_natives\platform-folders\src\index.js
- C:\Users\Simon\Documents\testapp\node_modules\nexe-natives\lib\require-native.js
- C:\Users\Simon\Documents\testapp\node_modules\nexe-natives\index.js
- C:\Users\Simon\Documents\testapp\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Users\Simon\.nexe_natives\platform-folders\src\index.js:5:15)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
```
the example of `node-pty` seems to work no problem?
ive also tried the `printer` npm module and thats fine too?
any suggestions where to look?

**Comment by si458** [comment]
scratch this...
it doesnt work with `printer` npm module either?
```
PS C:\Users\Simon\Documents\crap> .\testapp.exe
C:\Users\Simon\Documents\crap
internal/modules/cjs/loader.js:892
  throw err;
  ^
Error: Cannot find module 'printer'
Require stack:
- C:\Users\Simon\Documents\crap\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.resolve (internal/modules/cjs/helpers.js:98:19)
    at Object.<anonymous> (C:\Users\Simon\Documents\crap\index.js:3:21)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\Simon\\Documents\\crap\\index.js' ]
}
```
```
const { join } = require('path');
console.log(process.cwd());
console.log(require.resolve('printer'));
const printer = require('nexe-natives')(require.resolve('printer'), {
    localPath: join(__dirname, '.nexe_natives'),
    removeOnExit: false
});
console.log(printer);
```

**Comment by lrNas** [comment]
It's not working with node-hide-console-window also. Not sending the return to reduce verbose, but it's exactly the same.
